"""
notifier.py
-----------
Sends CloudSentrix scan findings to Slack or Microsoft Teams
via webhook URLs.

Setup:
  Slack : https://api.slack.com/messaging/webhooks
  Teams : https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/

Environment variables:
  CLOUDSENTRIX_SLACK_WEBHOOK  = https://hooks.slack.com/services/...
  CLOUDSENTRIX_TEAMS_WEBHOOK  = https://your-org.webhook.office.com/...

Public API
  send_notification(platform, findings, risk, cloud, source_file, webhook_url) -> bool
"""

from __future__ import annotations
import json, os, urllib.request, urllib.error
from dataclasses import dataclass

SLACK_ENV = "CLOUDSENTRIX_SLACK_WEBHOOK"
TEAMS_ENV = "CLOUDSENTRIX_TEAMS_WEBHOOK"

SEV_EMOJI  = {"CRITICAL":"🔴","HIGH":"🟠","MEDIUM":"🟡","LOW":"🟢"}
CLOUD_EMOJI= {"gcp":"☁️  GCP","aws":"🟡 AWS","azure":"🔷 Azure"}


@dataclass
class _Summary:
    cloud: str; source_file: str; score: int; rating: str
    total: int; critical: int; high: int; medium: int; low: int
    top_findings: list


def _summarise(findings, risk, cloud, source_file) -> _Summary:
    counts = {"CRITICAL":0,"HIGH":0,"MEDIUM":0,"LOW":0}
    top = []
    for f in findings:
        sev = f.severity.name if hasattr(f.severity,"name") else str(f.severity)
        counts[sev] = counts.get(sev,0) + 1
        if len(top) < 5:
            top.append({
                "rule_id": f.rule_id, "title": f.title, "severity": sev,
                "principal": getattr(f,"principal_id",getattr(f,"principal_name","")),
                "mitre": getattr(f,"mitre_technique_id",getattr(f,"mitre_technique","")),
            })
    rating = risk.rating.value if hasattr(getattr(risk,"rating",None),"value") else str(getattr(risk,"rating",""))
    return _Summary(cloud=cloud, source_file=source_file,
                    score=risk.score, rating=rating,
                    total=len(findings),
                    critical=counts.get("CRITICAL",0), high=counts.get("HIGH",0),
                    medium=counts.get("MEDIUM",0),     low=counts.get("LOW",0),
                    top_findings=top)


def _color(score):
    return "#43a047" if score>=70 else "#fb8c00" if score>=40 else "#e53935"


def _post(url, payload) -> bool:
    try:
        data = json.dumps(payload).encode()
        req  = urllib.request.Request(url, data=data,
               headers={"Content-Type":"application/json"}, method="POST")
        with urllib.request.urlopen(req, timeout=10) as r:
            return r.status in (200,201,202,204)
    except urllib.error.HTTPError as e:
        print(f"[notifier] HTTP {e.code}: {e.reason}"); return False
    except urllib.error.URLError as e:
        print(f"[notifier] Connection error: {e.reason}"); return False
    except Exception as e:
        print(f"[notifier] Error: {e}"); return False


# ── Slack ────────────────────────────────────────────────────────────────────

def _slack_payload(s: _Summary) -> dict:
    bar  = "█"*round(s.score/10) + "░"*(10-round(s.score/10))
    clr  = _color(s.score)
    lbl  = CLOUD_EMOJI.get(s.cloud.lower(), s.cloud)
    hdr  = (":rotating_light: *CloudSentrix Alert* — " if s.critical>0 else ":shield: *CloudSentrix Scan* — ") + lbl

    finding_blocks = []
    for f in s.top_findings:
        finding_blocks.append({"type":"section","text":{"type":"mrkdwn","text":
            f"{SEV_EMOJI.get(f['severity'],'⚪')} *[{f['rule_id']}]* {f['title']}\n"
            f">Principal: `{f['principal']}`  |  MITRE: `{f['mitre']}`"}})

    blocks = [
        {"type":"header","text":{"type":"plain_text","text":"🔐 CloudSentrix Security Alert","emoji":True}},
        {"type":"section","text":{"type":"mrkdwn","text":hdr}},
        {"type":"divider"},
        {"type":"section","fields":[
            {"type":"mrkdwn","text":f"*Score*\n`{bar}` *{s.score}/100* ({s.rating})"},
            {"type":"mrkdwn","text":f"*Findings*\n{s.total} total"},
            {"type":"mrkdwn","text":f"*Breakdown*\n{SEV_EMOJI['CRITICAL']} {s.critical}  {SEV_EMOJI['HIGH']} {s.high}  {SEV_EMOJI['MEDIUM']} {s.medium}  {SEV_EMOJI['LOW']} {s.low}"},
            {"type":"mrkdwn","text":f"*Source*\n`{s.source_file}`"},
        ]},
        {"type":"divider"},
        {"type":"section","text":{"type":"mrkdwn","text":"*Top Findings:*"}},
        *finding_blocks,
        {"type":"divider"},
        {"type":"context","elements":[{"type":"mrkdwn",
          "text":"Generated by *CloudSentrix* — github.com/Talha-Imran-cloud/cloudsentrix"}]},
    ]
    return {"blocks":blocks,"attachments":[{"color":clr,"blocks":[]}]}


def notify_slack(findings, risk, cloud, source_file, webhook_url=None) -> bool:
    url = webhook_url or os.environ.get(SLACK_ENV,"")
    if not url:
        print(f"[notifier] Slack webhook not set. Set env: {SLACK_ENV}=https://hooks.slack.com/...")
        return False
    s  = _summarise(findings, risk, cloud, source_file)
    ok = _post(url, _slack_payload(s))
    print(f"[notifier] {'✅' if ok else '❌'} Slack alert {'sent' if ok else 'failed'} — {s.total} finding(s)")
    return ok


# ── Teams ────────────────────────────────────────────────────────────────────

def _teams_payload(s: _Summary) -> dict:
    bar = "█"*round(s.score/10) + "░"*(10-round(s.score/10))
    lbl = CLOUD_EMOJI.get(s.cloud.lower(), s.cloud)
    clr = _color(s.score).lstrip("#")

    finding_lines = ""
    for f in s.top_findings:
        finding_lines += (
            f"{SEV_EMOJI.get(f['severity'],'⚪')} **[{f['rule_id']}]** {f['title']}  \n"
            f"&nbsp;&nbsp;&nbsp;&nbsp;Principal: `{f['principal']}`  \n"
        )

    return {
        "@type":"MessageCard","@context":"https://schema.org/extensions",
        "themeColor": clr,
        "summary": f"CloudSentrix — {s.total} finding(s) on {lbl}",
        "title":   f"🔐 CloudSentrix Security Alert — {lbl}",
        "sections":[
            {
                "activityTitle":    f"Score: `{bar}` **{s.score}/100** ({s.rating})",
                "activitySubtitle": f"Source: `{s.source_file}`",
                "facts":[
                    {"name":"Total Findings","value":str(s.total)},
                    {"name":f"{SEV_EMOJI['CRITICAL']} Critical","value":str(s.critical)},
                    {"name":f"{SEV_EMOJI['HIGH']} High",        "value":str(s.high)},
                    {"name":f"{SEV_EMOJI['MEDIUM']} Medium",    "value":str(s.medium)},
                    {"name":f"{SEV_EMOJI['LOW']} Low",          "value":str(s.low)},
                ],
                "markdown":True,
            },
            {"title":"Top Findings","text":finding_lines or "No findings.","markdown":True},
            {"text":"Generated by **CloudSentrix** — [github.com/Talha-Imran-cloud/cloudsentrix](https://github.com/Talha-Imran-cloud/cloudsentrix)","markdown":True},
        ],
    }


def notify_teams(findings, risk, cloud, source_file, webhook_url=None) -> bool:
    url = webhook_url or os.environ.get(TEAMS_ENV,"")
    if not url:
        print(f"[notifier] Teams webhook not set. Set env: {TEAMS_ENV}=https://your-org.webhook.office.com/...")
        return False
    s  = _summarise(findings, risk, cloud, source_file)
    ok = _post(url, _teams_payload(s))
    print(f"[notifier] {'✅' if ok else '❌'} Teams alert {'sent' if ok else 'failed'} — {s.total} finding(s)")
    return ok


# ── Public API ───────────────────────────────────────────────────────────────

def send_notification(platform, findings, risk, cloud, source_file, webhook_url=None) -> bool:
    p = platform.lower().strip()
    if p == "slack":
        return notify_slack(findings, risk, cloud, source_file, webhook_url)
    if p in ("teams","msteams","microsoft-teams"):
        return notify_teams(findings, risk, cloud, source_file, webhook_url)
    print(f"[notifier] Unknown platform '{platform}'. Use 'slack' or 'teams'.")
    return False


# ── Smoke test ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("CloudSentrix Notifier — Setup Guide")
    print("=" * 45)
    print()
    print("SLACK:")
    print("  1. Go to: https://api.slack.com/apps")
    print("  2. Create app -> Incoming Webhooks -> Add webhook")
    print("  3. Copy webhook URL")
    print(f"  4. Set env: {SLACK_ENV}=<url>")
    print("  5. Run: cloudsentrix scan --file my.json --notify slack")
    print()
    print("TEAMS:")
    print("  1. Teams -> channel -> ... -> Connectors")
    print("  2. Add 'Incoming Webhook' -> Configure -> Copy URL")
    print(f"  3. Set env: {TEAMS_ENV}=<url>")
    print("  4. Run: cloudsentrix scan --file my.json --notify teams")
    print()
    print(f"Slack webhook : {'SET' if os.environ.get(SLACK_ENV) else 'NOT SET'}")
    print(f"Teams webhook : {'SET' if os.environ.get(TEAMS_ENV) else 'NOT SET'}")
